=== G-Node/gogs/conf/dmp/json_schema/dmp_meti_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/product.schema.json",
    "title": "DMPschema-METI",
    "description": "DMP schema of METI",
    "type": "object",
    "properties": {
        "schema": {
            "type": "string"
        },
        "dmpType": {
            "type": "string"
        },
        "agreementTitle": {
            "type": "string"
        },
        "agreementDate": {
            "type": "string"
        },
        "submitDate": {
            "type": "string"
        },
        "corporateName": {
            "type": "string"
        },
        "researches": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "index": {
                            "type": "integer"
                        },
                        "title": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "manager": {
                            "type": "string"
                        },
                        "dataType": {
                            "type": "string"
                        },
                        "releaseLevel": {
                            "type": "integer"
                        },
                        "concealReason": {
                            "type": "string"
                        },
                        "concealPeriod": {
                            "type": "string"
                        },
                        "acquirer": {
                            "type": "string"
                        },
                        "acquireMethod": {
                            "type": "string"
                        },
                        "remarks": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "index",
                        "title",
                        "description",
                        "manager",
                        "dataType",
                        "releaseLevel",
                        "concealReason",
                        "concealPeriod",
                        "acquirer",
                        "acquireMethod",
                        "remarks"
                    ]
                }
            ]
        }
    },
    "required": [
        "schema",
        "dmpType",
        "agreementTitle",
        "agreementDate",
        "submitDate",
        "corporateName",
        "researches"
    ]
}

=== G-Node/gogs/conf/dmp/dmp_meti.json
{
    "schema": "meti",
    "dmpType": "New",
    "agreementTitle": "The Data Management Plan",
    "agreementDate": "2021-09-20",
    "submitDate": "2021-10-01",
    "corporateName": "The Corporate",
    "researches": [
        {
            "index": 1,
            "title": "The Research Data",
            "description": "This is description.",
            "manager": "John Doe",
            "dataType": "My Data",
            "releaseLevel": 4,
            "concealReason": "nothing",
            "concealPeriod": "",
            "acquirer": "John Lab",
            "acquireMethod": "by download link",
            "remarks": ""
        },
        {
            "index": 2,
            "title": "The Research Data2",
            "description": "This is description.",
            "manager": "Jumpei Kuwata",
            "dataType": "My Data",
            "releaseLevel": 4,
            "concealReason": "nothing",
            "concealPeriod": "",
            "acquirer": "IVIS Lab",
            "acquireMethod": "by download link",
            "remarks": ""
        }
    ]
}
